version: "3"

services:
  # ================================= Bot =====================================
  # Generic Rasa bot, used to run console for example.
  bot:
    # public: true
    build:
      context: .
      dockerfile: ./docker/bot.Dockerfile
    container_name: bot
    ports:
      - 5005:5005
    networks:
      - production
    depends_on:
      - actions
    restart: unless-stopped
    command: run --enable-api --cors "*"
  # ================================= Actions =================================
  # Rasa middleware used to connect with external APIs.
  actions:
    build:
      context: .
      dockerfile: ./docker/actions.Dockerfile
    container_name: actions
    ports:
      - 5055:5055
    networks:
      - production
  # ================================= Website =================================
  # Simple website with Rasa chat widget.
  web:
    build:
      context: . 
      dockerfile: ./docker/web.Dockerfile
    container_name: web
    ports:
      - 3000:3000
    networks:
      - production
    depends_on:
      - bot
      - actions

networks: 
    production:
        driver: bridge